language: node_js

env:
  SSH_USER: root
  APP_PATH: /root/trackingCoins1

sudo: false

git:
  depth: false

branches:
  only:
    - master

addons:
  ssh_known_hosts: $SSH_HOST

before_install:
  - openssl aes-256-cbc -K $encrypted_c9e88d9eac23_key -iv $encrypted_c9e88d9eac23_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./.travis/id_rsa

install: false

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c '
    rsync docker-compose.yml $SSH_USER@$SSH_HOST:$APP_PATH/
    && ssh root@$SSH_HOST "systemctl restart coins"'
  on:
    branch: master

